spring.application.name=library-api

# H2 Databaseの設定

# DBのコンソール画面（管理画面）を有効にする
spring.h2.console.enabled=true

# DBの場所（メモリ上に 'testdb' という名前で作る）
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver

# ログインIDとパスワード（練習用なのでシンプルに）
spring.datasource.username=sa
spring.datasource.password=

# SQLをログに出力する（裏で何が起きているか見えるようにする）
spring.jpa.show-sql=true